insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('湍急','tuān jí','/view/202602.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('酗酒','xù jiǔ','/view/2103.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('绚丽','xuàn lì','/view/526533.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('造诣','zào yì','/view/826198.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('哺育','bǔ yù','/view/775286.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('怂恿','sǒng yǒng','/view/1408.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('赏赐','shǎng cì','/view/1331315.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('笺书','jiān shū','/view/5738310.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('贮存','zhù cún','/view/669920.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('阐述','chǎn shù','/view/620953.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('澎湃','péng pài','/subview/44646/11114557.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('簇拥','cù yōng','/view/581275.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('濒临','bīn lín','/view/221373.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('逮捕','dài bǔ','/subview/31164/5117494.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('粗糙','cū cāo','/view/1184963.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('拂晓','fú xiǎo','/subview/428020/5136604.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('炽热','chì rè','/view/667261.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('发酵','fā jiào','/view/35695.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('狙击','jū jī','/subview/350578/8083427.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('酝酿','yùn niàng','/subview/358850/5087356.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('干涸','gān hé','/view/949415.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('畸形','jī xíng','/view/108116.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('干涸','gān hé','/view/949415.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('畸形','jī xíng','/view/108116.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('铿锵','kēng qiāng','/view/203842.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('抚恤','fǔ xù','/view/679888.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('吸吮','xī shǔn','/view/1324265.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('按捺','àn nà','/view/395773.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('塑料','sù liào','/view/30598.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('浸透','jìn tòu','/view/796437.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('粗犷','cū guǎng','/view/596168.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('高耸','gāo sǒng','/view/830430.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('证券','zhèng quàn','/subview/17039/4965178.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('呆板','dāi bǎn','/view/339067.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('凹陷','āo xiàn','/view/398118.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('提防','dī fáng','/view/1214743.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('屏息','bǐng xī','/view/793613.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('亲家','qìng jia','/subview/102480/11256015.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('参差不齐','cēn cī bù qí','/view/78820.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('自怨自艾','zì yuàn zì yì','/view/50478.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('否极泰来','pǐ jí tài lái','/view/98193.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('心宽体胖','xīn kuān tǐ pán','/view/93079.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('一曝十寒','yī pù shí hán','/view/246831.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('松弛','sōng chí','/view/208340.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('一筹莫展','yī chóu mò zhǎn','/view/79275.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('川流不息','chuān liú bù xī','/subview/78871/5139879.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('精粹','jīng cuì','/view/805257.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('重叠','chóng dié','/view/2101760.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('度假村','dù jià cūn','/view/60321.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('妨碍','fáng ài','/view/535053.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('辐射','fú shè','/subview/2121/5277577.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('天翻地覆','tiān fān dì fù','/subview/371059/8063235.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('气概','qì gài','/view/241308.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('悬梁刺股','xuán liáng cì gǔ','/view/171372.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('一鼓作气','yī gǔ zuò qì','/subview/36130/5072327.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('粗犷','cū guǎng','/view/596168.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('食不果腹','shí bù guǒ fù','/view/142827.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('凑合','còu hé','/view/1214370.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('候车室','hòu chē shì','/view/205430.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('迫不及待','pò bù jí dài','/subview/129755/9817369.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('即使','jí shǐ','/view/392970.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('一如既往','yī rú jì wǎng','/view/91462.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('挖墙脚','wā qiáng jiǎo','/view/426.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('不胫而走','bù jìng ér zǒu','/view/88285.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('竣工','jùn gōng','/view/138980.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('死皮赖脸','sǐ pí lài liǎn','/view/372296.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('再接再厉','zài jiē zài lì','/view/119534.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('老两口','lǎo liǎng kǒu','/view/1587119.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('黄粱美梦','huáng liáng měi mèng','/view/262895.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('水龙头','shuǐ lóng tóu','/view/25794.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('蛛丝马迹','zhū sī mǎ jì','/subview/76696/10523556.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('明信片','míng xìn piàn','/view/48686.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('墨守成规','mò shǒu chéng guī','/view/81902.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('大拇指','dà mǔ zhǐ','/view/659648.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('呕心沥血','ǒu xīn lì xuè','/view/71756.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('平添','píng tiān','/view/887032.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('出其不意','chū qí bù yì','/subview/166461/10735055.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('青睐','qīng lài','/subview/805834/5126600.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('入场券','rù chǎng quàn','/view/396007.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('声名鹊起','shēng míng què qǐ','/view/540403.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('谈笑风生','tán xiào fēng shēng','/view/157749.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('人情世故','rén qíng shì gù','/subview/130186/11097032.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('有恃无恐','yǒu shì wú kǒng','/subview/48979/11257696.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('追溯','zhuī sù','/view/588856.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('鬼鬼祟祟','guǐ guǐ suì suì','/view/92073.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('金榜题名','jīn bǎng tí míng','/subview/118667/11089553.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('走投无路','zǒu tóu wú lù','/subview/47041/8677940.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('趋之若鹜','qū zhī ruò wù','/view/142527.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('九霄云外','jiǔ xiāo yún wài','/subview/86459/11035031.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('宣泄','xuān xiè','/view/388781.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('寒暄','hán xuān','/view/116011.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('赝品','yàn pǐn','/subview/299692/6432660.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('不能自已','bù néng zì yǐ','/view/106340.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('竭泽而渔','jié zé ér yú','/view/87565.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('滥竽充数','làn yú chōng shù','/view/28700.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('世外桃源','shì wài táo yuán','/subview/32023/5073000.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('赃款','zāng kuǎn','/view/1429496.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('蛰伏','zhé fú','/view/556692.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('装帧','zhuāng zhēn','/view/110412.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('饮鸩止渴','yǐn zhèn zhǐ kě','/view/29259.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('坐镇','zuò zhèn','/view/1414191.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('旁征博引','páng zhēng bó yǐn','/subview/160666/9404073.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('炙手可热','zhì shǒu kě rè','/view/76726.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('坐月子','zuò yuè zǐ','/view/148.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('隘口','ài kǒu','/view/152630.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('暧昧','ài mèi','/subview/5960/4940139.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('按捺','àn nà','/view/395773.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('懊恼','ào nǎo','/view/540461.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('凋敝','diāo bì','/view/1309018.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('拨弄','bō nòng','/view/713997.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('贬斥','biǎn chì','/view/3441079.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('边陲','biān chuí','/view/658269.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('荟萃','huì cuì','/view/657575.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('璀璨','cuǐ càn','/subview/545506/5066344.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('摧毁','cuī huǐ','/view/1560690.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('磋商','cuō shāng','/view/1316140.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('诋毁','dǐ huǐ','/view/1174326.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('真谛','zhēn dì','/subview/102815/10775755.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('嫡亲','dí qīn','/view/970113.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('叠韵','dié yùn','/view/312492.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('更迭','gēng dié','/view/707227.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('烦琐','fán suǒ','/view/1148796.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('就范','jiù fàn','/view/654202.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('购销','gòu xiāo','/view/801032.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('诡秘','guǐ mì','/view/713600.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('诡计','guǐ jì','/subview/918597/11092456.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('辜负','gū fù','/view/393832.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('瑰丽','guī lì','/view/203708.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('灌输','guàn shū','/view/710196.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('涵养','hán yǎng','/view/457176.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('涣散','huàn sàn','/view/737780.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('撒谎','sā huǎng','/view/555685.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('装潢','zhuāng huáng','/view/174356.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('幌子','huǎng zi','/view/174337.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('诙谐','huī xié','/view/1255984.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('蛊惑','gǔ huò','/subview/342630/11092389.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('教诲','jiào huì','/view/425185.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('伎俩','jì liǎng','/subview/349153/5119998.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('贫瘠','pín jí','/view/529110.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('姣好','jiāo hǎo','/view/772747.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('阵脚','zhèn jiǎo','/view/1536920.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('疏浚','shū jùn','/view/45913.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('崛起','jué qǐ','/subview/661293/5085620.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('诀窍','jué qiào','/view/824819.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('沮丧','jǔ sàng','/subview/615611/11092633.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('迥然','jiǒng rán','/view/811602.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('拮据','jié jū','/view/782032.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('勘误','kān wù','/view/831446.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('犒劳','kào láo','/view/250096.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('恪守','kè shǒu','/view/841043.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('垮台','kuǎ tái','/view/580839.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('恳求','kěn qiú','/view/812133.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('叩门','kòu mén','/view/4613418.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('狂澜','kuáng lán','/view/695059.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('炼乳','liàn rǔ','/view/39511.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('沥青','lì qīng','/view/123295.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('清冽','qīng liè','/view/747384.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('伶俐','líng lì','/view/787438.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('遴选','lín xuǎn','/view/855862.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('屠戮','tú lù','/view/392710.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('蔓延','màn yán','/subview/359785/5084467.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('怠慢','dài màn','/view/831067.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('谩骂','màn mà','/view/386227.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('贸然','mào rán','/view/1117837.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('诬蔑','wū miè','/view/621822.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('泯灭','mǐn miè','/subview/47930/9294300.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('临摹','lín mó','/view/158589.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('牟利','móu lì','/view/1189716.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('招募','zhāo mù','/view/743971.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('懦弱','nuò ruò','/view/48485.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('怄气','òu qì','/view/521506.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('蹒跚','pán shān','/view/83941.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('匾额','biǎn é','/view/100521.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('剽窃','piāo qiè','/view/522411.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('接洽','jiē qià','/view/778011.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('默契','mò qì','/subview/718104/6848852.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('分歧','fēn qí','/subview/679637/8062709.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('告罄','gào qìng','/view/568872.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('苍穹','cāng qióng','/subview/46127/8749801.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('趋势','qū shì','/view/204171.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('痊愈','quán yù','/subview/1175044/9619038.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('商榷','shāng què','/view/362143.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('发轫','fā rèn','/view/364513.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('熟稔','shú rěn','/view/891237.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('蹂躏','róu lìn','/view/540448.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('偌大','ruò dà','/view/1310256.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('害臊','hài sào','/view/2530923.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('晌午','shǎng wǔ','/view/218762.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('慑服','shè fú','/view/916612.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('放肆','fàng sì','/subview/677269/5286223.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('厮杀','sī shā','/view/846991.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('怂恿','sǒng yǒng','/view/1408.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('宿将','sù jiàng','/view/1133228.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('拖沓','tuō tà','/view/391027.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('糟蹋','zāo tà','/view/545496.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('熏陶','xūn táo','/view/1326195.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('袒护','tǎn hù','/view/1049737.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('搪塞','táng sè','/view/900166.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('搪瓷','táng cí','/view/143610.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('誊写','téng xiě','/view/616675.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('剔除','tī chú','/view/226857.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('妥帖','tuǒ tiē','/view/987285.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('唾弃','tuò qì','/view/1445262.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('推诿','tuī wěi','/view/295060.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('诬告','wū gào','/view/2457239.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('会晤','huì wù','/view/362246.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('翔实','xiáng shí','/view/386147.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('帽檐','mào yán','/view/2475075.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('怏然','yàng rán','/view/1461376.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('遭殃','zāo yāng','/view/1418181.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('谒见','yè jiàn','/view/248406.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('游弋','yóu yì','/view/333203.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('演绎','yǎn yì','/view/593981.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('逸事','yì shì','/view/901641.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('作揖','zuō yī','/view/1069772.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('荫庇','yìn bì','/view/1201151.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('荣膺','róng yīng','/view/730809.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('墙垣','qiáng yuán','/view/707226.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('纷纭','fēn yún','/view/926853.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('授予','shòu yǔ','/view/1004559.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('精湛','jīng zhàn','/view/807343.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('昭雪','zhāo xuě','/view/727888.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('瞻仰','zhān yǎng','/view/695347.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('蛰伏','zhé fú','/view/556692.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('缜密','zhěn mì','/view/629962.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('胡诌','hú zhōu','/view/695304.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('安步当车','ān bù dàng chē','/view/36344.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('胴体','dòng tǐ','/view/986093.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('飞来横祸','fēi lái hèng huò','/view/150709.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('给予','jǐ yǔ','/subview/156364/6756168.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('眼睑','yǎn jiǎn','/view/24590.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('绢花','juàn huā','/view/824790.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('粳米','jīng mǐ','/view/80387.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('籼米','xiān mǐ','/view/343814.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('靓妆','jìng zhuāng','/view/720618.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('前倨后恭','qián jù hòu gōng','/view/114583.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('以儆效尤','yǐ jǐng xiào yóu','/view/434.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('倥偬','kǒng zǒng','/view/310011.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('傀儡','kuǐ lěi','/subview/53604/5119618.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('书声琅琅','shū shēng láng láng','/view/786309.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('扪心自问','mén xīn zì wèn','/subview/176373/11122801.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('披靡','pī mǐ','/view/1718134.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('拘泥','jū nì','/view/817417.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('牵强附会','qiān qiǎng fù huì','/view/100949.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('请柬','qǐng jiǎn','/subview/148082/11094412.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('禅让','shàn ràng','/view/19089.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('妥帖','tuǒ tiē','/view/987285.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('相机行事','xiàng jī xíng shì','/view/566662.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('铜臭','tóng xiù','/view/102516.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('倾轧','qīng yà','/view/706878.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('筵席','yán xí','/view/33288.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('梦魇','mèng yǎn','/view/137598.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('笑靥','xiào yè','/view/285122.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('荫凉','yìn liáng','/view/1978723.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('年逾古稀','nián yú gǔ xī','/view/43835.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('伛偻','yǔ lǚ','/view/391479.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('鹬蚌相争','yù bàng xiāng zhēng','/subview/51793/11152647.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('怨声载道','yuàn shēng zài dào','/view/85287.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('择菜','zhái cài','/view/726274.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('动辄','dòng zhé','/view/309576.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('症结','zhēng jié','/view/410579.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('踯躅','zhí zhú','/view/453043.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('抵掌','zhǐ zhǎng','/view/936316.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('白术','bái zhú','/view/72030.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('琢磨','zuó mo','/subview/1051876/7583528.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('琢磨','zuó mo','/subview/1051876/7583528.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('篱笆','lí bā','/view/653509.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('襁褓','qiǎng bǎo','/view/19806.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('期期艾艾','qī qī ài ài','/view/119670.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('自怨自艾','zì yuàn zì yì','/view/50478.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('枸杞','gǒu qǐ','/view/11163.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('搅和','jiǎo huo','/view/186285.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('草莽','cǎo mǎng','/subview/331982/9173267.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('酩酊','mǐng dǐng','/view/1005121.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('没奈何','mò nài hé','/view/873767.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('媲美','pì měi','/view/825139.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('退避三舍','tuì bì sān shè','/view/18049.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('拱券','gǒng xuàn','/view/335994.htm',0,NULL,0,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('囹圄','líng yǔ','/subview/279505/11090329.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('羞赧','xiū nǎn','/view/416764.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('箜篌','kōng hóu','/view/17226.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('觊觎','jì yú','/view/330453.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('龃龉','jǔ yǔ','/view/14020.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('魍魉','wǎng liǎng','/subview/403208/5647567.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('纨绔','wán kù','/subview/342209/5241519.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('佝偻','gōu lóu','/view/328250.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('龟裂','jūn liè','/view/229927.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('蓓蕾','bèi lěi','/view/373708.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('蹀躞','dié xiè','/view/61038.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('狡黠','jiǎo xiá','/view/448794.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('猥亵','wěi xiè','/view/41209.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('蟾蜍','chán chú','/view/9795.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('迷惘','mí wǎng','/subview/998271/7386411.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('趔趄','liè qie','/view/378393.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('窥觑','kuī qù','/view/814752.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('肄业','yì yè','/view/657578.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('徜徉','cháng yáng','/view/108610.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('叱咤','chì zhà','/view/303735.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('绸缪','chóu móu','/view/583334.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('纶巾','guān jīn','/view/76745.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('咄嗟','duō jiē','/view/1171202.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('龌龊','wò chuò','/view/41546.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('促狭','cù xiá','/view/844136.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('皈依','guī yī','/subview/22435/5063811.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('旮旯','gā lá','/view/19021.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('戛然','jiá rán','/view/337942.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('参差','cēn cī','/view/825689.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('鳏夫','guān fū','/view/637722.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('髑髅','dú lóu','/view/335586.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('皴裂','cūn liè','/view/1063140.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('妊娠','rèn shēn','/subview/33344/9897377.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('老鸨','lǎo bǎo','/view/33022.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('孑孓','jié jué','/view/25228.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('逡巡','qūn xún','/view/263447.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('趑趄','zī jū','/view/323179.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('斡旋','wò xuán','/view/334010.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('弹劾','tán hé','/view/19387.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('旌旗','jīng qí','/view/805237.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('沟壑','gōu hè','/view/697718.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('交媾','jiāo gòu','/view/278426.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('菁华','jīng huá','/view/630631.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('拈花','niān huā','/subview/3047780/6030175.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('旖旎','yǐ nǐ','/view/201944.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('褴褛','lán lǚ','/view/635773.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('执拗','zhí niù','/view/81317.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('匍匐','pú fú','/view/409510.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('拥趸','yōng dǔn','/subview/53113/11040591.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('氤氲','yīn yūn','/view/344410.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('鹄的','gǔ dì','/view/956475.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('整饬','zhěng chì','/view/158582.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('贲临','bì lín','/view/2109702.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('踽踽独行','jǔ jǔ dú xíng','/view/730335.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('舐犊','shì dú','/view/1382600.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('单于','chán yú','/subview/173349/11232305.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('噱头','xué tou','/view/726246.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('木讷','mù nè','/view/418135.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('薄荷','bò he','/view/18986.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('徘徊','pái huái','/subview/385312/5109363.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('耆宿','qí sù','/view/817781.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('确凿','què záo','/view/703224.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('枣核','zǎo hé','/view/473258.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('给予','jǐ yǔ','/subview/156364/6756168.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('腌臜','ā zā','/view/323154.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('迤逦','yǐ lǐ','/view/54616.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('耄耋','mào dié','/view/24605.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('彳亍','chì chù','/subview/182467/8949679.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('谄媚','chǎn mèi','/view/1004455.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('女红','nǚ gōng','/view/89730.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('恬静','tián jìng','/view/543045.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('包庇','bāo bì','/view/406872.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('唾弃','tuò qì','/view/1445262.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('谄媚','chǎn mèi','/view/1004455.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('棘手','jí shǒu','/subview/621914/11090082.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('谒见','yè jiàn','/view/248406.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('舐犊','shì dú','/view/1382600.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('箴言','zhēn yán','/subview/369718/5064328.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('翌日','yì rì','/view/462430.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('恪守','kè shǒu','/view/841043.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('麻痹','má bì','/view/91238.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('玷污','diàn wū','/view/182330.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('罹难','lí nàn','/view/880703.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('嗾使','sǒu shǐ','/view/936342.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('饿殍','è piǎo','/view/1089816.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('鞭笞','biān chī','/view/191030.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('嗔怒','chēn nù','/view/629958.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('憧憬','chōng jǐng','/view/256757.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('翩跹','piān xiān','/view/879391.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('蓦然','mò rán','/view/453213.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('糟粕','zāo pò','/view/566672.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('掮客','qián kè','/subview/67184/5120805.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('怙恶不悛','hù è bù quān','/view/129791.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('脍炙','kuài zhì','/view/112770.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('褴褛','lán lǚ','/view/635773.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('愤懑','fèn mèn','/view/679187.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('龋齿','qǔ chǐ','/view/40825.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('冗长','rǒng cháng','/view/593982.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('回溯','huí sù','/view/699271.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('鞭挞','biān tà','/view/191033.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('狡黠','jiǎo xiá','/view/448794.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('媲美','pì měi','/view/825139.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('讣告','fù gào','/view/40562.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('斡旋','wò xuán','/view/334010.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('联袂','lián mèi','/view/885875.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('赈济','zhèn jì','/view/743730.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('汲取','jí qǔ','/view/689314.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('刚愎自用','gāng bì zì yòng','/view/64709.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('窠臼','kē jiù','/view/189139.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('潸然泪下','shān rán lèi xià','/view/387989.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('妊娠','rèn shēn','/subview/33344/9897377.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('阴霾','yīn mái','/view/1413.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('砧板','zhēn bǎn','/view/721080.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('揠苗助长','yà miáo zhù zhǎng','/subview/60931/8681165.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('修葺','xiū qì','/view/1133292.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('悚然','sǒng rán','/view/1448900.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('惴惴不安','zhuì zhuì bù ān','/view/65268.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('栉风沐雨','zhì fēng mù yǔ','/view/90968.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('桎梏','zhì gù','/view/300842.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('瞠目','chēng mù','/view/1159934.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('膏肓','gāo huāng','/view/98414.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('咳嗽','ké sòu','/view/43167.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('百舸','bǎi gě','/view/558045.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('淙淙','cóng cóng','/view/203835.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('针砭','zhēn biān','/view/302048.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('莅临','lì lín','/view/740775.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('谬论','miù lùn','/view/517112.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('喟然长叹','kuì rán cháng tàn','/view/421986.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('要挟','yāo xié','/view/726854.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('拓片','tà piàn','/view/224961.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('禅让','shàn ràng','/view/19089.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('叨扰','tāo rǎo','/view/966454.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('咯血','kǎ xiě','/view/535663.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('侧歪','zhāi wāi','/view/1433259.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('审时度势','shěn shí duó shì','/view/271672.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('鳏夫','guān fū','/view/637722.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('针砭','zhēn biān','/view/302048.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('舶来品','bó lái pǐn','/view/34602.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('言简意赅','yán jiǎn yì gāi','/view/256728.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('草菅人命','cǎo jiān rén mìng','/view/44651.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('矫揉造作','jiǎo róu zào zuò','/view/85334.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('不落窠臼','bù luò kē jiù','/view/68197.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('脍炙人口','kuài zhì rén kǒu','/view/45069.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('杀戮','shā lù','/subview/97825/8830631.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('痉挛','jìng luán','/view/192315.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('美轮美奂','měi lún měi huàn','/view/127290.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('啰嗦','luō suo','/subview/1289825/6486677.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('萎靡不振','wěi mǐ bù zhèn','/view/79398.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('沉湎','chén miǎn','/view/615287.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('罄竹难书','qìng zhú nán shū','/view/50090.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('发轫','fā rèn','/view/364513.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('瘙痒病','sào yǎng bìng','/view/7778812.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('额手称庆','é shǒu chēng qìng','/view/248196.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('床笫之私','chuáng zǐ zhī sī','/view/106735.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('恣意妄为','zì yì wàng wéi','/view/50485.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('编纂','biān zuǎn','/view/564386.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('谙熟','ān shú','/view/822036.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('针砭','zhēn biān','/view/302048.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('文牍','wén dú','/view/493914.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('藩篱','fān lí','/view/783051.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('樊篱','fán lí','/subview/625873/7812356.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('睥睨','bì nì','/view/619171.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('壕堑','háo qiàn','/view/3311517.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('卫戍','wèi shù','/view/611262.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('矍铄','jué shuò','/view/310225.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('魑魅魍魉','chī mèi wǎng liǎng','/view/226.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('裨益','bì yì','/view/441164.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('觥筹交错','gōng chóu jiāo cuò','/view/81728.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('合卺','hé jǐn','/view/71730.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('僭越','jiàn yuè','/view/102832.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('疆埸','jiāng yì','/view/393294.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('狡狯','jiǎo kuài','/view/1307878.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('秕糠','bǐ kāng','/view/340164.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('畚箕','běn jī','/view/279201.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('氤氲','yīn yūn','/view/344410.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('袅袅','niǎo niǎo','/view/940992.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('娉婷','pīng tíng','/view/374195.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('熠熠','yì yì','/view/203648.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('熙熙攘攘','xī xī rǎng rǎng','/view/63024.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('磅礴','páng bó','/view/202385.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('逶迤','wēi yí','/view/567666.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('狡黠','jiǎo xiá','/view/448794.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('龃龉','jǔ yǔ','/view/14020.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('耄耋','mào dié','/view/24605.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('倥偬','kǒng zǒng','/view/310011.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('猥獕','wěi cuī','/view/3777989.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('委蛇','wēi yí','/view/531940.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('趔趄','liè qie','/view/378393.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('窥觑','kuī qù','/view/814752.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('咄嗟','duō jiē','/view/1171202.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('罹难','lí nàn','/view/880703.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('鳏夫','guān fū','/view/637722.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('皴裂','cūn liè','/view/1063140.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('逡巡','qūn xún','/view/263447.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('趑趄','zī jū','/view/323179.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('鹄的','gǔ dì','/view/956475.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('腌臜','ā zā','/view/323154.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('胼胝','pián zhī','/view/29990.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('趔趄','liè qie','/view/378393.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('隽永','juàn yǒng','/view/51498.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('纵横捭阖','zòng héng bǎi hé','/view/41361.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('醍醐灌顶','tí hú guàn dǐng','/view/1545.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('踽踽','jǔ jǔ','/view/635369.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('迤逦','yǐ lǐ','/view/54616.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('旖旎','yǐ nǐ','/view/201944.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('汪洋恣肆','wāng yáng zī sì','/view/811184.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('沆瀣一气','hàng xiè yī qì','/view/122373.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('骅骝','huá liú','/subview/876506/9747940.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('畚箕','běn jī','/view/279201.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('羼杂','chàn zá','/view/1390283.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('霓裳羽衣','ní cháng yǔ yī','/subview/437669/11151656.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('薅草','hāo cǎo','/view/936275.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('矫枉过正','jiǎo wǎng guò zhèng','/view/252817.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('酩酊大醉','mǐng dǐng dà zuì','/view/245868.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('泥淖','ní nào','/view/740793.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('忸怩','niǔ ní','/view/1039939.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('睥睨','bì nì','/view/619171.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('一曝十寒','yī pù shí hán','/view/246831.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('蹊跷','qī qiāo','/view/77949.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('襁褓','qiǎng bǎo','/view/19806.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('荏苒','rěn rǎn','/view/194652.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('玛瑙','mǎ nǎo','/view/10559.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('箪食壶浆','dān sì hú jiāng','/view/171183.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('叨光','tāo guāng','/view/699701.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('轻佻','qīng tiāo','/view/1297439.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('骁将','xiāo jiàng','/view/138475.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('迤逦','yǐ lǐ','/view/54616.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('良莠不分','liáng yǒu bù fēn','/view/1549557.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('谮言','zèn yán','/view/878734.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('札记','zhá jì','/view/1414.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('卷帙浩繁','juàn zhì hào fán','/view/165773.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('渣滓','zhā zǐ','/view/621947.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('畚箕','běn jī','/view/279201.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('槟榔','bīng láng','/view/31242.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('颠簸','diān bǒ','/view/730709.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('簸箕','bò ji','/view/78027.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('采邑','cài yì','/view/772239.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('蹭蹬','cèng dèng','/view/1527968.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('谄媚','chǎn mèi','/view/1004455.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('经幢','jīng chuáng','/view/8314.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('一撮','yī zuǒ','/view/3039147.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('一沓','yī dá','/view/3041481.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('大纛','dà dào','/view/911861.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('棠棣','táng dì','/subview/418155/10281442.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('簠簋','fǔ guǐ','/view/1171244.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('准噶尔','zhǔn gá ěr','/subview/215012/11043020.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('芥蓝','gài lán','/view/80142.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('戆头戆脑','gàng tóu gàng nǎo','/view/8020786.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('力能扛鼎','lì néng gāng dǐng','/view/535453.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('估衣','gù yī','/view/705348.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('哈士蟆','hà shì má','/view/125656.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('薅草','hāo cǎo','/view/936275.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('诨号','hùn hào','/view/837566.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('佶屈聱牙','jí qū áo yá','/view/152688.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('连篇累牍','lián piān lěi dú','/view/257368.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('炮烙','páo luò','/view/141294.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('棕榈','zōng lǘ','/view/33519.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('箪食壶浆','dān sì hú jiāng','/view/171183.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('嗾使','sǒu shǐ','/view/936342.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('尿脬','suī pāo','/view/1043136.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('缩砂密','sù shā mì','/view/249543.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('遂心如意','suì xīn rú yì','/view/696174.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('趿拉','tā lā','/view/706669.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('喁喁','yóng yóng','/view/1037090.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('妯娌','zhóu lǐ','/view/78616.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('怔忪','zhēng zhōng','/view/1271537.htm',0,NULL,1,0);
insert or ignore into WordDataTable(title,pinyin,url,wrong,wordtype,level,isRight) values('床笫','chuáng zǐ','/view/907361.htm',0,NULL,1,0);
